### ISSUE TITLE
可以加个  meta 适配下手机

### ISSUE THREAD

**Issue by xuanzhi33** [Blokura/bv2av#10]
加个这个：  
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

**Comment by xuanzhi33** [comment]
`  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">`

**Comment by Blokura** [comment]
已完成 感谢建议
