### ISSUE TITLE
算法更新建议

### ISSUE THREAD

**Issue by ccicnce113424** [Blokura/bv2av#2]
新s:11, 10, 3, 8, 4, 6, 2, 9, 5, 7
add:100618342136696320
AV2BV里面的result可以改成"BV          "
然后循环次数改一下

**Comment by ccicnce113424** [comment]
说一下，我移植Java的时候也差点犯了优先级错误

**Comment by Blokura** [comment]
感谢反馈 JS版其实是抄的(手动滑稽) 没有细看代码
刚刚按照建议进行了修改QAQ
