### ISSUE TITLE
1R7411y7Tb出现负数

### ISSUE THREAD

**Issue by GSUI5051** [Blokura/bv2av#3]
在线转换页面上出现负数
![VTV(2FV NDYQ1}( P3952@7](https://user-images.githubusercontent.com/23095566/77510005-c52f6480-6ea8-11ea-8ae2-8e9873cf4adb.png)
对应的AV号是av99162421

**Comment by Blokura** [comment]
这是个好问题 PHP代码可以解析出来 JS我是扒的搞不懂（滑稽）

**Comment by mrhso** [comment]
怎么不 at 我（
等等我自己的网站怎么没问题（
![image](https://user-images.githubusercontent.com/13294467/77514427-ce70ff00-6eb1-11ea-97dc-c53871307dbf.png)
测了这个网站也没有问题。
![image](https://user-images.githubusercontent.com/13294467/77514475-eb0d3700-6eb1-11ea-9088-8f48e5c96435.png)
请问您的浏览器支援 ES6 吗？最好是给出浏览器，我这边 Node.js 和 Chrome 都是正常的。

**Comment by ccicnce113424** [comment]
我的锅。
刚才我没讲清楚，JS里面循环次数也应该改的。
修复完的程序已经Pull request
如果可以解决问题，就可以close了

**Comment by Blokura** [comment]
> 我的锅。
> 刚才我没讲清楚，JS里面循环次数也应该改的。
> 修复完的程序已经Pull request
> 如果可以解决问题，就可以关闭了

知乎的大佬又给改回去了XD
![image](https://user-images.githubusercontent.com/21168605/77515588-bd28f200-6eb3-11ea-995b-7614e1e5ee01.png)

**Comment by kaixin-365** [comment]
> 怎么不 at 我（
> 等等我自己的网站怎么没问题（
> ![image](https://user-images.githubusercontent.com/13294467/77514427-ce70ff00-6eb1-11ea-97dc-c53871307dbf.png)
> 测了这个网站也没有问题。
> ![image](https://user-images.githubusercontent.com/13294467/77514475-eb0d3700-6eb1-11ea-9088-8f48e5c96435.png)
> 请问您的浏览器支援 ES6 吗？最好是给出浏览器，我这边 Node.js 和 Chrome 都是正常的。

大佬您的网站不支持IE，F12会提示av及bv未定义。

**Comment by ccicnce113424** [comment]
所以，解决了？

**Comment by mrhso** [comment]
> > 怎么不 at 我（
> > 等等我自己的网站怎么没问题（
> > ![image](https://user-images.githubusercontent.com/13294467/77514427-ce70ff00-6eb1-11ea-97dc-c53871307dbf.png)
> > 测了这个网站也没有问题。
> > ![image](https://user-images.githubusercontent.com/13294467/77514475-eb0d3700-6eb1-11ea-9088-8f48e5c96435.png)
> > 请问您的浏览器支援 ES6 吗？最好是给出浏览器，我这边 Node.js 和 Chrome 都是正常的。
> 
> 大佬您的网站不支持IE，F12会提示av及bv未定义。

我写 JS 都是 ES6 起步，const 这种东西我想 IE 不支援也正常……
