### ISSUE TITLE
IE浏览器无法使用

### ISSUE THREAD

**Issue by kaixin-365** [Blokura/bv2av#7]
F12提示错误为 av及bv未定义。
![批注 2020-03-25 155744](https://user-images.githubusercontent.com/39674311/77514227-64f0f080-6eb1-11ea-86fa-04b050c6005a.png)

**Comment by mrhso** [comment]
可能 IE 不支援 ES6，我写 JS 是 ES6 起步。

**Comment by byyxx128** [comment]
IE就算了吧……IE连GitHub都没法用……Chromium核的Edge不香么……

**Comment by Blokura** [comment]
IE建议通过 https://bv2av.com/?BV=av170001 或 https://bv2av.com/video/bv17x411w7KC 这种链接进入查询
