### ISSUE TITLE
使用API的时候不能自动检测是AV还是BV号

### ISSUE THREAD

**Issue by ccicnce113424** [Blokura/bv2av#8]
这就导致了这样一个错误：
![image](https://user-images.githubusercontent.com/30774232/77528520-12bbc980-6ec9-11ea-84ab-33bacd0b454e.png)
纱雾好评

**Comment by Blokura** [comment]
![image](https://user-images.githubusercontent.com/21168605/77529436-8dd1af80-6eca-11ea-925f-4a0b4bb1cf20.png)
修好啦~~
