### ISSUE TITLE
关于获取视频封面不能直接显示的问题2333

### ISSUE THREAD

**Issue by xiexinhua2006** [Blokura/bv2av#9]
啊我是那个fork提交美化UI的，想问下之前我的代码里有个Bug不能获取视频封面必须自己手动打开一遍那个封面的链接才能显示的Bug是怎么修复的2333
刚学php，入坑极浅的小白2333

**Comment by Blokura** [comment]
emmmm不是很能理解你这个BUG是什么个情况 能详细写一下吗？最好是配图给我看看

**Comment by xiexinhua2006** [comment]
enmmmm
https://bv2av.drblack-system.com/
你随便输一个没输过的BV号看下能显示出封面吗，我这里不行，但是你的网站就可以..迷惑

**Comment by kaixin-365** [comment]
> enmmmm
> https://bv2av.drblack-system.com/
> 你随便输一个没输过的BV号看下能显示出封面吗，我这里不行，但是你的网站就可以..迷惑

看看是不是CSS的问题，应该事先做下F12调试嘛。
![批注 2020-03-27 103221](https://user-images.githubusercontent.com/39674311/77715768-69371e00-7017-11ea-88be-7df6b3c8600f.jpg)

**Comment by Blokura** [comment]
感谢楼上的回复，刚刚看了一下，是因为B站对于图片资源有防盗链措施，封面图片有referrer时不能够加载。
因此应当在header部分添加 `<meta name="referrer" content="no-referrer">`使得页面加载文件时不携带访问的网站referrer
